version: '3.8'

services:
  django:
    image: atiqullah/task_ai:latest  # Replace with your Docker Hub image tag
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - DEBUG=True  # Set your environment variables here
    env_file:
      - .env

  celery:
    image: atiqullah/task_ai:latest  # Replace with your Docker Hub image tag
    command: celery -A task_ai.app.handlers worker --loglevel=info
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    env_file:
      - .env


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

