version: '3.8'

services:
  django:
    image: atiqullah/task_ai:latest
    # build: .
    command: bash entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - celery
    environment:
      - DEBUG=True
    env_file:
      - .env

  celery:
    image: atiqullah/task_ai:latest
    # build: .
    command: bash celery_entrypoint.sh
    depends_on:
      - rabbitmq
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    env_file:
      - .env


  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

