version: '3.8'

services:
  django:
    image: atiqullah/task_ai:latest
    command: bash docker/entrypoints/django.sh
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  celery:
    image: atiqullah/task_ai:latest
    command: bash docker/entrypoints/celery.sh
    depends_on:
      - rabbitmq
    env_file:
      - ../.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:

