name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      OPENAI_PARSING_ASST_ID: ${{ secrets.OPENAI_PARSING_ASST_ID }}
      OPENAI_CATEGORIZING_ASST_ID: ${{ secrets.OPENAI_CATEGORIZING_ASST_ID }}
      OPENAI_PARSING_THREAD_ID: ${{ secrets.OPENAI_PARSING_THREAD_ID }}
      OPENAI_CATEGORIZING_THREAD_ID: ${{ secrets.OPENAI_CATEGORIZING_THREAD_ID }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python manage.py test
